{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cn.core",
    "module": "utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.0.0.aar",
          "url": "utils-1.0.0.aar",
          "size": 101887,
          "sha512": "5677e1514789d9d5f8bfa10fa3385e4b6c1486ee16029b71046b899355aff1eef071a61e590947673029118cbe4fd50c017cd2ac0b063c0d97787ff5e8ceb632",
          "sha256": "46cac41ce8c2499ce47e907d0ea31f2590f2d69493e66fccf310bfb46088b7e4",
          "sha1": "d2bfaec27c47a4c62ec6265a467886b3a21042fe",
          "md5": "58aff65c9262311d8ce92734a2b5e411"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.0.0.aar",
          "url": "utils-1.0.0.aar",
          "size": 101887,
          "sha512": "5677e1514789d9d5f8bfa10fa3385e4b6c1486ee16029b71046b899355aff1eef071a61e590947673029118cbe4fd50c017cd2ac0b063c0d97787ff5e8ceb632",
          "sha256": "46cac41ce8c2499ce47e907d0ea31f2590f2d69493e66fccf310bfb46088b7e4",
          "sha1": "d2bfaec27c47a4c62ec6265a467886b3a21042fe",
          "md5": "58aff65c9262311d8ce92734a2b5e411"
        }
      ]
    }
  ]
}
