{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cn.core",
    "module": "msg-router-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.cn.core",
          "module": "andlinker",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "msg-router-client-1.0.0.aar",
          "url": "msg-router-client-1.0.0.aar",
          "size": 70414,
          "sha512": "adcf6966d950e6c26ab3d379dc7a1950cc3060a2169d608c6a302f5f099de64033527495278a1e96af1ea14ccb1baf72775f71be1f5b71c5ab6d822ed7e81f6d",
          "sha256": "9b42fc90df90af75c068f61f997f5218a306cd28e1fff472048df7bf1c9f5ceb",
          "sha1": "696b20422fac34dfb3cb3f2f1c10deeaa36a6fe0",
          "md5": "d96e3580379f34ed9206a5349fa71fc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.cn.core",
          "module": "andlinker",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "msg-router-client-1.0.0.aar",
          "url": "msg-router-client-1.0.0.aar",
          "size": 70414,
          "sha512": "adcf6966d950e6c26ab3d379dc7a1950cc3060a2169d608c6a302f5f099de64033527495278a1e96af1ea14ccb1baf72775f71be1f5b71c5ab6d822ed7e81f6d",
          "sha256": "9b42fc90df90af75c068f61f997f5218a306cd28e1fff472048df7bf1c9f5ceb",
          "sha1": "696b20422fac34dfb3cb3f2f1c10deeaa36a6fe0",
          "md5": "d96e3580379f34ed9206a5349fa71fc7"
        }
      ]
    }
  ]
}
