{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cn.core",
    "module": "resources",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-1.0.0.aar",
          "url": "resources-1.0.0.aar",
          "size": 76400,
          "sha512": "d19d27466ba8b8eb0b5602690444c1f8fa4d78b5364ede16c29847b64d0de6f1aa6936bfffb70bd8628a9f7bffc2c71877afea5249c3584f822c29bcd22dac92",
          "sha256": "39fdb1b8d4eff12b9683ad33bfe79860645ff6098cc3c8c5411807dfb504252c",
          "sha1": "1491afec49cf938c8d99fd3a0651cc558d182e64",
          "md5": "88f18ec3bb0a2ca2f0b15451285d4352"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-1.0.0.aar",
          "url": "resources-1.0.0.aar",
          "size": 76400,
          "sha512": "d19d27466ba8b8eb0b5602690444c1f8fa4d78b5364ede16c29847b64d0de6f1aa6936bfffb70bd8628a9f7bffc2c71877afea5249c3584f822c29bcd22dac92",
          "sha256": "39fdb1b8d4eff12b9683ad33bfe79860645ff6098cc3c8c5411807dfb504252c",
          "sha1": "1491afec49cf938c8d99fd3a0651cc558d182e64",
          "md5": "88f18ec3bb0a2ca2f0b15451285d4352"
        }
      ]
    }
  ]
}
