{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cn.core",
    "module": "ui",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 466760,
          "sha512": "92aea76480ad70c82c2107bb593a511776dd23e927d6d17beff04a9b57cf1bbb297775f5c7e9710b5094df280bcf3d0b4f0fdae59dbb3e66e598bf3070747d72",
          "sha256": "0fc76d1cec77fca13d41035c0ea81bb9b80ad6a01c557da8dd5279722a7ef042",
          "sha1": "5b1a68b2099ece5b0549be10cb764442135199b9",
          "md5": "89e448641367dc77a9454990b7a63ee5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.cn.core",
          "module": "resources",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 466760,
          "sha512": "92aea76480ad70c82c2107bb593a511776dd23e927d6d17beff04a9b57cf1bbb297775f5c7e9710b5094df280bcf3d0b4f0fdae59dbb3e66e598bf3070747d72",
          "sha256": "0fc76d1cec77fca13d41035c0ea81bb9b80ad6a01c557da8dd5279722a7ef042",
          "sha1": "5b1a68b2099ece5b0549be10cb764442135199b9",
          "md5": "89e448641367dc77a9454990b7a63ee5"
        }
      ]
    }
  ]
}
